# Generated by Django 5.2.5 on 2026-07-14 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_weeklycheckin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='body_scans/')),
                ('muscle_scores', models.JSONField(default=dict)),
                ('posture_notes', models.TextField(blank=True, default='')),
                ('gemini_analysis', models.TextField(blank=True, default='')),
                ('week_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scan_date', '-created_at'],
            },
        ),
    ]
