# Generated by Django 5.2.5 on 2026-10-05 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0013_bodyscan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_json', models.TextField(blank=True, default='')),
                ('uploaded_files_json', models.TextField(blank=True, default='[]')),
                ('meal_plan_json', models.TextField(blank=True, default='')),
                ('training_plan_json', models.TextField(blank=True, default='')),
                ('bio_age_json', models.TextField(blank=True, default='')),
                ('critique_json', models.TextField(blank=True, default='')),
                ('audit_report', models.TextField(blank=True, default='')),
                ('corrections_json', models.TextField(blank=True, default='[]')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='workouts.clinicalsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
