# Generated by Django 5.2.5 on 2026-10-06 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0014_clinicalsession_clinicalchatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WearableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('raw_data_json', models.TextField(blank=True, default='')),
                ('tokens_json', models.TextField(blank=True, default='')),
                ('total_steps', models.IntegerField(default=0)),
                ('total_calories_burned', models.IntegerField(default=0)),
                ('total_active_mins', models.IntegerField(default=0)),
                ('total_sleep_hours', models.FloatField(default=0.0)),
                ('recovery_score', models.IntegerField(default=0)),
                ('avg_workout_performance', models.IntegerField(default=0)),
                ('average_hr', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wearable_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_synced'],
            },
        ),
    ]
